import type {GetServerSideProps, NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {AppSession, getSession} from "../lib/utils/get-session";
import {authorizeURL} from "../lib/utils/spotify";
import ConnectSpotifyButton from "../components/ConnectSpotifyButton";
import RandomTopTrack from "../components/RandomTopTrack";

type Props = AppSession & {authorizeURL: string}

const Home: NextPage<Props> = ({accessToken,authorizeURL}) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>SpotifyTopCollector</title>
                <meta name="description" content="Generated by create next app"/>
                {/*<link rel="icon" href="/favicon.ico"/>*/}
            </Head>

            <main className={styles.main}>
                {!accessToken ?
                    <RandomTopTrack />
                    :
                    <ConnectSpotifyButton authorizeURL={authorizeURL} />
                }
            </main>

            <footer className={styles.footer}>

            </footer>
        </div>
    )
}

export const getServerSideProps: GetServerSideProps = async ({req, res}) => {
    const session = await getSession(req, res)
    return {
        props: {
            accessToken: session.accessToken || null,
            authorizeURL,
        }
    }
}

export default Home
