import type {GetServerSideProps, NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import ConnectSpotifyButton from "../components/ConnectSpotifyButton";
import RandomTopTrack from "../components/RandomTopTrack";
import { withSessionSsr } from "../lib/withSession";
import {authorizeURL} from "../lib/utils/spotify";

type Props = { accessToken?: string | null } & {authorizeURL: string}

const Home: NextPage<Props> = ({accessToken, authorizeURL}) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>SpotifyTopCollector</title>
                <meta name="description" content="Generated by create next app"/>
                {/*<link rel="icon" href="/favicon.ico"/>*/}
            </Head>

            <main className={styles.main}>
                {accessToken ?
                    <RandomTopTrack/>
                    :
                    <ConnectSpotifyButton authorizeURL={authorizeURL}/>
                }
            </main>

            <footer className={styles.footer}>

            </footer>
        </div>
    )
}

export const getServerSideProps: GetServerSideProps = withSessionSsr(
    async  ({req}) => {
        return {
            props: {
                accessToken: req.session.accessToken || null,
                authorizeURL
            },
        };
    }
)

export default Home
